### ISSUE TITLE
Test Ticket

### ISSUE THREAD

**Issue by valentinajemuovic** [alptium/goran.savovic#1]
Hi @SavovicGoran ,

Please do the following:

1. Write a comment below that you have received this test ticket. 
2. Please tag me using @ then typing my GitHub name.
3. Then close this ticket.

Thanks,
Valentina

**Comment by SavovicGoran** [comment]
I have received the ticket @https://github.com/valentinacupac

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by valentinajemuovic** [comment]
Hi @SavovicGoran, it seems that you replied from your email, causing the message to have additional signature text. Please try again, but reply directly from GitHub.

**Comment by SavovicGoran** [comment]
Ok, let's try directly from here :)
@valentinacupac

**Comment by valentinajemuovic** [comment]
Hi @SavovicGoran, I see here that you changed the original Test Ticket to Hello World. However, for Hello World, it was necessary to create a new ticket. In general, for every task, a new ticket is created. So please re-close this ticket and create a new ticket for Hello World.

**Comment by valentinajemuovic** [comment]
@SavovicGoran , I changed the title back to the original title "Test Ticket" so closing this now.
