### ISSUE TITLE
Calculator

### ISSUE THREAD

**Issue by SavovicGoran** [alptium/goran.savovic#3]
@valentinacupac  da li ovde da napisem kod za program calculator?

**Comment by valentinajemuovic** [comment]
@SavovicGoran, please complete firstly the #2 task, from there you'll see where the code should go.

**Comment by SavovicGoran** [comment]
@valentinacupac  It's done.

**Comment by valentinajemuovic** [comment]
@SavovicGoran, the indentaton on line 8 is not stylistically correct.
https://github.com/alptium/valentina.cupac/wiki/03.-Hello-World comment 29.

**Comment by SavovicGoran** [comment]
@valentinacupac 
I have fixed indentation on line 8.
I have one question. If I want to practice in Eclipse do I have to make new
Java Project and change workspace?

**Comment by valentinajemuovic** [comment]
@SavovicGoran, formatting is now good, please add support for other operations (subtraction, multiplication, division).

P.S. For your practice, yes, make another separate workspace which is separate from this alptium work.

**Comment by SavovicGoran** [comment]
@valentinacupac It supports  other operations (subtraction, multiplication, division).

**Comment by valentinajemuovic** [comment]
@SavovicGoran, correct.
